version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  metascore:
    container_name: app
    restart: always
    build: .
    ports:
      - "4445:4445"
    links:
      - mongo