version: "3"
services:
  backend:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.production 
      args:
        port: ${PORT}
    env_file:
      - ../.env
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      WAIT_HOSTS: database:27017
  database:
    image: mongo:latest
    env_file:
      - ../.env
    expose:
      - 27017
    ports:
      - "27017:27017"
    command: "mongod --smallfiles"
  mongo-seed:
    build:
      context: ../
      dockerfile: docker/Dockerfile.seed
    links:
      - database